# Generated by Django 6.0.1 on 2026-02-02 10:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('advisor', 'Advisor (Agent)'), ('maintenance', 'Maintenance (Staff)'), ('admin', 'Admin')], default='advisor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_qualification', models.CharField(blank=True, default='MBBS', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Referred', 'Referred')], default='Assigned', max_length=50)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'advisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('referral_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Referral commission amount for the referring doctor/agent', max_digits=10)),
                ('admission_type', models.CharField(choices=[('OPD', 'Out-Patient Department (OPD)'), ('IPD', 'In-Patient Department (IPD)')], default='OPD', max_length=10)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('CANCELLED', 'Cancelled')], default='ADMITTED', max_length=20)),
                ('bed_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nursing_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctor_consultation_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('investigation_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('investigation_type', models.CharField(blank=True, choices=[('IN_HOUSE', 'In-House'), ('OUTSIDE', 'Outside')], default='IN_HOUSE', max_length=20)),
                ('procedural_surgical_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anaesthesia_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surgeon_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges_description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by_doctor', models.ForeignKey(blank=True, help_text='Doctor who referred this patient (linked to agent for commission tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.doctorreferral')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('illness', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'advisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('raised_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('allotted_budget', models.CharField(max_length=50)),
                ('fix_by', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('issue_category', models.CharField(max_length=50)),
                ('raised_by', models.ForeignKey(limit_choices_to={'role': 'maintenance'}, on_delete=django.db.models.deletion.CASCADE, related_name='raised_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20)),
                ('odometer_start_image', models.ImageField(blank=True, null=True, upload_to='trip_odometers/')),
                ('odometer_end_image', models.ImageField(blank=True, null=True, upload_to='trip_odometers/')),
                ('total_kilometers', models.FloatField(default=0.0)),
                ('additional_expenses', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'advisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OvernightStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.TextField()),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to='hotel_bills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overnight_stays', to='core.trip')),
            ],
        ),
        migrations.AddField(
            model_name='doctorreferral',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_referrals', to='core.trip'),
        ),
    ]
