# Generated by Django 6.0.1 on 2026-02-02 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreferral',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'advisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
