# Generated by Django 6.0.1 on 2026-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctorreferral_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreferral',
            name='address',
        ),
        migrations.AddField(
            model_name='doctorreferral',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorreferral',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorreferral',
            name='pin',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorreferral',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
