# Generated by Django 6.0.1 on 2026-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_alter_doctorreferral_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.CharField(blank=True, help_text='e.g. Vidarbha, West', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.CharField(default='Maharashtra', max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='e.g. Downtown, North Zone', max_length=100, unique=True),
        ),
    ]
