# Generated by Django 6.0.1 on 2026-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_area_description_area_region_area_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
