# Generated by Django 6.0.1 on 2026-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_area_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
