# Generated by Django 6.0.1 on 2026-02-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_doctorassignmenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAssignmentHistory',
        ),
    ]
