# Generated by Django 6.0.1 on 2026-02-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_admission_patient_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hardware_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hardware_id_authorized',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
