# Generated by Django 6.0.1 on 2026-02-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_backfill_patientreferral_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreferral',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientreferral',
            name='illness',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
