# Generated by Django 6.0.1 on 2026-02-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_patientreferral_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated total commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_category',
            field=models.CharField(choices=[('CASH', 'Cash'), ('INSURANCE', 'Insurance'), ('AYUSHMAN', 'Ayushman Bharat')], default='CASH', max_length=50),
        ),
        migrations.CreateModel(
            name='DoctorCommissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category', models.CharField(choices=[('CASH', 'Cash'), ('INSURANCE', 'Insurance'), ('AYUSHMAN', 'Ayushman Bharat')], max_length=50)),
                ('bed_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Bed Charges')),
                ('nursing_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Nursing Charges')),
                ('doctor_consultation_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Doctor Consultation')),
                ('investigation_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Investigation Charges')),
                ('procedural_surgical_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Procedural/Surgical')),
                ('anaesthesia_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Anaesthesia')),
                ('surgeon_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Surgeon Charges')),
                ('other_charges_rate', models.FloatField(default=0.0, help_text='Commission % for Other Charges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_profiles', to='core.doctorreferral')),
            ],
            options={
                'unique_together': {('doctor', 'payment_category')},
            },
        ),
    ]
