# Generated by Django 6.0.1 on 2026-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_admission_commission_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='referral_amount',
        ),
        migrations.AddField(
            model_name='admission',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorcommissionprofile',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='Standard Discount % for this category'),
        ),
    ]
