# Generated by Django 6.0.1 on 2026-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_paymentcategory_remove_admission_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreferral',
            name='visit_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_visits/'),
        ),
    ]
