# Generated by Django 6.0.1 on 2026-02-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_doctorreferral_visit_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAssignmentDoctorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_statuses', to='core.agentassignment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_statuses', to='core.doctorreferral')),
            ],
            options={
                'verbose_name_plural': 'Agent Assignment Doctor Statuses',
                'unique_together': {('assignment', 'doctor')},
            },
        ),
    ]
