# Generated by Django 6.0.1 on 2026-02-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_agentassignmentdoctorstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreferral',
            name='area',
        ),
        migrations.RemoveField(
            model_name='doctorreferral',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctorreferral',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='doctorreferral',
            name='street',
        ),
    ]
