# Generated by Django 6.0.1 on 2026-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_doctorreferral_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overnightstay',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='overnightstay',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
