# Generated by Django 6.0.1 on 2026-02-18 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_overnightstay_latitude_overnightstay_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignmentdoctorstatus',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentassignmentdoctorstatus',
            name='visit_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_visits', to='core.trip'),
        ),
        migrations.AddField(
            model_name='agentassignmentdoctorstatus',
            name='visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
