# Generated by Django 6.0.1 on 2026-02-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agentassignmentdoctorstatus_is_visited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-admission_date']},
        ),
        migrations.AlterModelOptions(
            name='doctorreferral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patientreferral',
            options={'ordering': ['-reported_on']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='doctorreferral',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Checked if the doctor is an internal doctor of the hospital.'),
        ),
    ]
