# Generated by Django 6.0.1 on 2026-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_admission_options_alter_doctorreferral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreferral',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Internal doctors do not need addresses and cannot be assigned to agents.'),
        ),
        migrations.AlterField(
            model_name='doctorreferral',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Referred', 'Referred'), ('Internal', 'Internal')], default='Assigned', max_length=50),
        ),
    ]
