# Generated by Django 6.0.1 on 2026-02-23 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_doctorreferral_is_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='referred_to_doctor',
            field=models.ForeignKey(blank=True, help_text='Internal doctor handling the admission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_received', to='core.doctorreferral'),
        ),
        migrations.AddField(
            model_name='patientreferral',
            name='referred_by_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_referred_out', to='core.doctorreferral'),
        ),
        migrations.AddField(
            model_name='patientreferral',
            name='referred_to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_referred_in', to='core.doctorreferral'),
        ),
    ]
